name: Compute SHA-256 on Release

on:
  release:
    types: [ published ]

jobs:
  compute-checksum:
    runs-on: ubuntu-latest

    steps:
      - name: Compute SHA-256 checksum
        run: |
          curl -sfL https://github.com/pongasoft/jamba/archive/refs/tags/${{ github.event.release.tag_name }}.zip | sha256sum > ${{ github.event.release.tag_name }}.zip_sha256.txt

      - name: Upload checksum to release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.event.release.tag_name }}.zip_sha256.txt
