name: Run Tests

on:
  push:
    branches: [ "github-actions" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: --release

jobs:
  run_tests:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure Project
        working-directory: ${{github.workspace}}
        run: ${{github.workspace}}/jamba-test-plugin/configure.py -- -DJAMBA_DOWNLOAD_VSTSDK=ON -DJAMBA_ENABLE_VST2=OFF

      - name: Run test action
        working-directory: ${{github.workspace}}/build
        run: ./jamba.sh ${{ env.BUILD_TYPE }} test
