name: Run Tests (Windows)

on:
  push:
    branches:
      - 'master'
    tags-ignore:
      - '*'

jobs:
  run_tests:
    strategy:
      matrix:
        os: [windows-2022, windows-2025]
        include:
          - generator: "Visual Studio 17 2022"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Project (dry run)
        working-directory: ${{github.workspace}}
        run: python ${{github.workspace}}\jamba-test-plugin\configure.py -n -G "${{ matrix.generator }}" -- -DJAMBA_DOWNLOAD_VSTSDK=ON -A x64

      - name: Configure Project
        working-directory: ${{github.workspace}}
        run: python ${{github.workspace}}\jamba-test-plugin\configure.py -G "${{ matrix.generator }}" -- -DJAMBA_DOWNLOAD_VSTSDK=ON -A x64

      - name: Run test/validate/archive (Release)
        working-directory: ${{github.workspace}}/build
        run: .\jamba.bat --release -b test validate archive

      - name: Run test/validate/archive (Debug)
        working-directory: ${{github.workspace}}/build
        run: .\jamba.bat -b test validate archive
