name: Run Tests (macOS)

on:
  push:
    branches: [ "github-actions" ]

jobs:
  run_tests:
    runs-on: [macos-11, macos-12, macos-13]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Project (dry run)
        working-directory: ${{github.workspace}}
        run: ${{github.workspace}}/jamba-test-plugin/configure.py -n -- -DJAMBA_DOWNLOAD_VSTSDK=ON -DJAMBA_ENABLE_VST2=OFF

      - name: Configure Project
        working-directory: ${{github.workspace}}
        run: ${{github.workspace}}/jamba-test-plugin/configure.py -- -DJAMBA_DOWNLOAD_VSTSDK=ON -DJAMBA_ENABLE_VST2=OFF

      - name: Run test/validate/archive (Release)
        working-directory: ${{github.workspace}}/build
        run: ./jamba.sh --release -b test validate archive

      - name: Run test/validate/archive (Debug)
        working-directory: ${{github.workspace}}/build
        run: ./jamba.sh -b test validate archive
