name: Run Tests (macOS)

on:
  push

jobs:
  run_tests:
    strategy:
      matrix:
        os: [macos-11, macos-12]
        # macos-13 is currently beta so not included

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Project (dry run)
        working-directory: ${{github.workspace}}
        run: ${{github.workspace}}/jamba-test-plugin/configure.py -n -- -DJAMBA_DOWNLOAD_VSTSDK=ON

      - name: Configure Project
        working-directory: ${{github.workspace}}
        run: ${{github.workspace}}/jamba-test-plugin/configure.py -- -DJAMBA_DOWNLOAD_VSTSDK=ON

      - name: Run test/validate/archive (Release)
        working-directory: ${{github.workspace}}/build
        run: ./jamba.sh --release -b test validate archive

      - name: Run test/validate/archive (Debug)
        working-directory: ${{github.workspace}}/build
        run: ./jamba.sh -b test validate archive
